<template>
  <ul class="customers">
    <CustomerLogoBlock
      link="https://studio.blender.org/"
      element-key="blender-invert"
      name="Blender"
    />
    <CustomerLogoBlock
      link="https://www.supamonks.com/"
      element-key="supamonks-invert"
      name="Supamonks"
    />
    <CustomerLogoBlock
      link="https://www.gizmosite.tv/"
      element-key="gizmo-invert"
      name="Gizmosite"
    />
    <CustomerLogoBlock
      link="https://www.miyu.fr/"
      element-key="miyu-invert"
      name="Miyu"
    />
    <CustomerLogoBlock
      link="https://www.polycat.com/"
      element-key="polycat"
      name="Polycat"
    />
    <CustomerLogoBlock
      link="https://www.mikrofilm.no/"
      element-key="mikrofilm-invert"
      name="Mikrofilm"
    />
    <CustomerLogoBlock
      link="https://bartmaalderink.nl/"
      element-key="bart-invert"
      name="Bart Maalderink"
    />
    <CustomerLogoBlock
      link="http://www.enclume-animation.com/"
      element-key="enclume-invert"
      name="Enclume"
    />
    <CustomerLogoBlock
      link="https://nki.tv/"
      element-key="nki"
      name="NKI"
    />
    <CustomerLogoBlock
      link="https://woodblock.tv/"
      element-key="woodblock"
      name="Wooblock"
    />
    <CustomerLogoBlock
      link="https://www.stimstudio.com/en/"
      element-key="stim"
      name="Stim Studio"
    />
    <CustomerLogoBlock
      link="https://www.viridianfx.co.uk/"
      element-key="viridian"
      name="ViridianVFX"
    />
    <CustomerLogoBlock
      link="https://www.dirtylooks.co.uk/"
      element-key="dirty-looks"
      name="Dirty Looks"
    />
    <CustomerLogoBlock
      link="https://heckler.tv/"
      element-key="heckler"
      name="Heckler"
    />
    <CustomerLogoBlock
      link="https://rabbitsfootstudios.se/"
      element-key="rabbitsfoot"
      name="Rabbit's Foot"
    />
    <CustomerLogoBlock
      link="https://animaskin.no/"
      element-key="animaskin"
      name="Animaskin"
    />
    <CustomerLogoBlock
      link="https://animaltank.com/"
      element-key="animaltank"
      name="Animaltank"
    />
    <CustomerLogoBlock
      link="https://floating-rock.com/"
      element-key="floatingrock"
      name="Floating Rock"
    />
    <CustomerLogoBlock
      link="https://novanima.eu/"
      element-key="novanima"
      name="Novanima"
    />
    <CustomerLogoBlock
      link="https://www.squarefilms.fr/"
      element-key="squarefilms"
      name="Square Films"
    />
    <CustomerLogoBlock
      link="https://wizz.fr/en"
      element-key="wizz"
      name="Wizz"
    />
    <CustomerLogoBlock
      link="https://www.warriorsvfx.com.br/"
      element-key="warriorsvfx"
      name="Warriors VFX"
    />
    <CustomerLogoBlock
      link="https://www.imagovfx.com/"
      element-key="imagovfx"
      name="Imago VFX"
    />
    <CustomerLogoBlock
      link="https://www.ovfx.com/"
      element-key="outlookvfx"
      name="Outlook VFX"
    />
    <CustomerLogoBlock
      link="https://tetsuoanimation.com/"
      element-key="tetsuo"
      name="Tetsuo Animation"
    />
    <CustomerLogoBlock
      link="https://www.holybird.fr/"
      element-key="holybird"
      name="Holy Bird"
    />
    <CustomerLogoBlock
      link="https://www.3dar.com/"
      element-key="3dar"
      name="3DAR"
    />
    <CustomerLogoBlock
      link="http://www.ateliervfx.com/"
      element-key="atelier-vfx"
      name="Atelier VFX"
    />
    <CustomerLogoBlock
      link="https://www.emberlight.se/"
      element-key="emberlight"
      name="Emberlight"
    />
    <CustomerLogoBlock
      link="https://www.nfb.ca/"
      element-key="nfb"
      name="NFB"
    />
    <CustomerLogoBlock
      link="https://pikkukala.com/"
      element-key="pikkukala"
      name="Pikkukala"
    />
    <CustomerLogoBlock
      link="https://pyjama.fi/"
      element-key="pyjama"
      name="Pyjama Studios"
    />
    <CustomerLogoBlock
      link="https://circlestudio.com.my/"
      element-key="circle"
      name="Circle Studios"
    />
    <CustomerLogoBlock
      link="https://bus.group/"
      element-key="busgroup"
      name="Bus Group"
    />
    <CustomerLogoBlock
      link="https://lesfilmsdupoissonrouge.com/"
      element-key="les-films-du-poisson-rouge"
      name="Les films du poisson rouge"
    />
    <CustomerLogoBlock
      link="https://krndsh.com/"
      element-key="karendash"
      name="Karendash"
    />
    <CustomerLogoBlock
      link="https://www.aparat-studio.com/"
      element-key="aparat"
      name="Aparat"
    />
    <CustomerLogoBlock
      link="https://www.odcreate.me"
      element-key="odee"
      name="Odee"
    />
    <CustomerLogoBlock
      link="https://www.monkeys.tv/"
      element-key="monkeys"
      name="Monkeys"
    />
    <CustomerLogoBlock
      link="https://rockinvfx.com/"
      element-key="rockinvfx"
      name="Rockin VFX"
    />
    <CustomerLogoBlock
      link="https://cousinbizarre.com/"
      element-key="cousin-bizarre"
      name="Cousin Bizarre"
    />
    <CustomerLogoBlock
      link="http://www.signos.com.co/"
      element-key="signos"
      name="Signos"
    />
    <CustomerLogoBlock
      link="https://naive.se/"
      element-key="naive"
      name="Naive"
    />
    <CustomerLogoBlock
      link="https://www.werlenmeyer.com/"
      element-key="werlen-meyer"
      name="Werlen Meyer"
    />
    <CustomerLogoBlock
      link="https://nikopicto.com/"
      element-key="niko-picto"
      name="Niko Picto"
    />
  </ul>
</template>
